Stampit/Stampit.Webapp/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Chart.Mvc.ComplexChart;
using Chart.Mvc.SimpleChart;
using Stampit.Logic.Interface;
using System.Threading.Tasks;
using Stampit.Entity;
using Stampit.CommonType;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "Manager")]
    public class StatisticController : Controller
    {
        private IProductRepository ProductRepository { get; }
        private ICompanyRepository CompanyRepository { get; }
        private IEnduserRepository EnduserRepository { get; }
        private IStampcardRepository StampcardRepository { get; }

        public StatisticController(IProductRepository productRepository, ICompanyRepository companyRepository, IEnduserRepository enduserRepository, IStampcardRepository stampcardRepository)
        {
            this.ProductRepository = productRepository;
            this.CompanyRepository = companyRepository;
            this.EnduserRepository = enduserRepository;
            this.StampcardRepository = stampcardRepository;
        }

        // GET: Statistic
        public ActionResult Index()
        {
            return View();
        }

        // GET: StampCardStatistics
        public ActionResult CardsInCirculation()
        {
            var currentCompany = CompanyRepository.FindByIdAsync(Session[Setting.SESSION_COMPANY].ToString()).Result;
            var total = StampcardRepository.CountStampcardsFromCompany(currentCompany).Result;
            var redeemed = StampcardRepository.CountRedeemedStampcardsFromCompany(currentCompany).Result;
            var unredeemed = total-redeemed;
            List<SimpleData> data = new List<SimpleData> {
                new SimpleData
                {
                    Value = redeemed,
                    Color = "#46BFBD",
                    Highlight = "#5AD3D1",
                    Label = "Redeemed Cards"
                },
                new SimpleData
                {
                    Value = unredeemed,
                    Color = "#FDB45C",
                    Highlight = "#FFC870",
                    Label = "Unredeemed Cards"
                }

            };
            return PartialView(data);
        }

        // GET: CardStatusStatistics
        public ActionResult CardStatus()
        {
            var currentCompany = CompanyRepository.FindByIdAsync(Session[Setting.SESSION_COMPANY].ToString()).Result;
            var stampcardsCompany = StampcardRepository.GetAllStampcardsFromCompany(currentCompany).Result;

            var stampcards = from s in stampcardsCompany
                             select new BarChartDTO
                             {
                                 BarChart = new BarChart
                                 {
                                     ComplexData = new ComplexData
                                     {
                                         Labels = (from data in s.Value
                                                   select data.Key.ToString()).ToList(),
                                         Datasets = (from data in s.Value
                                                     select new ComplexDataset
                                                     {
                                                         Data = s.Value.Values.Select(val => (double)val).ToList(),
                                                         FillColor = "rgba(220,220,220,0.2)"
                                                     }).Take(1).ToList()
                                     }
                                 },
                                Product = s.Key
                             };

            return PartialView(stampcards);
        }

        // GET: SalesStatistics
        public ActionResult Sales()
        {
            var currentCompany = CompanyRepository.FindByIdAsync(Session[Setting.SESSION_COMPANY].ToString()).Result;
            var salesProduct = ProductRepository.SalesPerProduct(currentCompany).Result;

            Tupel<string,string> randColor;

            var sales = from p in salesProduct
                    select new SimpleData {
                        Value = p.Value,
                        Color = (randColor = RandomColor()).Arg1,
                        Highlight = randColor.Arg2,
                        Label = p.Key.Productname
                    };
            
            return PartialView(sales);
        }

        // GET: CustomerStatistics
        public ActionResult Customer()
        {
            var currentCompany = CompanyRepository.FindByIdAsync(Session[Setting.SESSION_COMPANY].ToString()).Result;
            var countEnduser = EnduserRepository.CountEnduser(currentCompany).Result;
            return PartialView(countEnduser);
        }

        private static Random rand = new Random(System.Environment.TickCount);

        private Tupel<string,string> RandomColor()
        {
            string[] hex = new string[] {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F"};

            string result = "#";
            string highlightResult = "#";
            for (int i = 0; i < 6; i++)
            {
                int next = rand.Next(0, hex.Length - 1);
                result += hex[next];
                highlightResult += hex[next + 2 > 15 ? 15 : next + 2];
            }

            return new Tupel<string, string>(result,highlightResult);
        }
    }

    public class BarChartDTO
    {
        public Product Product { get; set; }
        public BarChart BarChart { get; set; }
    }    
}

Stampit/Stampit.Webapp/Views/Statistic/CardStatus.cshtml
@using Stampit.Webapp.Controllers;
@using Chart.Mvc.ComplexChart;
@using Chart.Mvc.Extensions;
@model IEnumerable<BarChartDTO>

<script src="~/Scripts/Chart.js"></script>

@{
    int cnt = 0;
    foreach (var item in Model)
    {
        string canvasName = "cardStatusCanvas" + cnt + "";
        cnt++;
        <h4>@(item?.Product?.Productname ?? "Kein Product")</h4>

        <div>
            <canvas id="@canvasName" width="400" height="400"></canvas>
            @Html.CreateChart(canvasName, item.BarChart)
        </div>
    }
}

Stampit/Stampit.Webapp/Views/Statistic/CardsInCirculation.cshtml
@model IEnumerable<SimpleData>
@using Chart.Mvc.SimpleChart;
@using Chart.Mvc.Extensions;

<script src="~/Scripts/Chart.js"></script>

@{
    var pieChart = new PieChart();
    pieChart.Data.AddRange(Model);
}
<div>
    <canvas id="cardsInCirculationCanvas" width="400" height="400"></canvas>
    @Html.CreateChart("cardsInCirculationCanvas", pieChart)
</div>
<br />
<div>
    @{
        double sum = 0;
        foreach (var item in Model)
        {
            sum += item.Value;
        }
        <h4>Total stampcards: @sum </h4>
    }
</div>

Stampit/Stampit.Webapp/Views/Statistic/Customer.cshtml
@model long

<h4>Total customers: @Model</h4>

Stampit/Stampit.Webapp/Views/Statistic/Index.cshtml
<a name="StampsStempelkarten"></a>

<br />

@if (string.IsNullOrEmpty(Session["companyID"]?.ToString()))
{
	<h1>No Company selected</h1>
}
else
{
	<h1 align="center">Statistics</h1>
	<h2>Stampcard statistics</h2>
	{
		Html.RenderAction("CardsInCirculation", "Statistic");
	}
	<br />
	<br />

	{
		Html.RenderAction("CardStatus", "Statistic");
	}

	<br/>
	<br/>

	<a name="Umsatz"></a>
	<h2>Sales statistics</h2>
	{
		Html.RenderAction("Sales", "Statistic");
	}

	<br />
	<br />

	<a name="Kunden"></a>
	<h2>Customer statistics</h2>
	{
		Html.RenderAction("Customer", "Statistic");
	}

	<br />
	<br />
}

Stampit/Stampit.Webapp/Views/Statistic/Sales.cshtml
@model IEnumerable<SimpleData>
@using Chart.Mvc.SimpleChart;
@using Chart.Mvc.Extensions;

<script src="~/Scripts/Chart.js"></script>

@{
    var pieChart = new PieChart();
    pieChart.Data.AddRange(Model);
}
<div>
    <canvas id="salesCanvas" width="400" height="400"></canvas>
    @Html.CreateChart("salesCanvas", pieChart)
</div>
<br/>
<div>
    @{
        double sum = 0.0;
        foreach (var item in Model)
        {
            sum += item.Value;
        }
        <h4>Total sales: @sum €</h4>
    }
</div>