Stampit/Stampit.Webapp/Controllers/KioskModeController.cs
using Stampit.CommonType;
using Stampit.Entity;
using Stampit.Logic.Interface;
using Stampit.Webapp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "KioskUser,Manager")]
    public class KioskModeController : Controller
    {
        private IProductRepository ProductRepository { get; }
        private ICompanyRepository CompanyRepository { get; }
        private IQrCodeGenerator QrCodeGenerator { get; }
        private IStampCodeProvider StampCodeProvider { get; }
        private IStampCodeService StampCodeService { get; }

        private Company currentCompany;

        public KioskModeController(IQrCodeGenerator qrCodeGenerator, IStampCodeProvider stampCodeProvider, IStampCodeService stampCodeService, IProductRepository productRepository, ICompanyRepository companyRepository)
        {
            this.ProductRepository = productRepository;
            this.CompanyRepository = companyRepository;
            this.QrCodeGenerator = qrCodeGenerator;
            this.StampCodeService = stampCodeService;
            this.StampCodeProvider = stampCodeProvider;
        }

        public async Task<ActionResult> Index()
        {
            var sessionState = Session[Setting.SESSION_PRODUCTS] as SessionState;
            var comId = Session[Setting.SESSION_COMPANY]?.ToString();
            if (string.IsNullOrEmpty(comId)) return View();

            if (sessionState == null)
            {
                this.currentCompany = (await CompanyRepository.FindByIdAsync(comId));

                sessionState = new SessionState { Model = new List<ProductViewModel>() };
                foreach (var product in await ProductRepository.FindProductsFromCompany(this.currentCompany, 0))
                {
                    sessionState.Model.Add(new ProductViewModel { Product = product, Count = 0, IsSelected = !sessionState.Model.Any() });
                }
                sessionState.SelectedViewModel = sessionState.Model.FirstOrDefault();
                Session[Setting.SESSION_PRODUCTS] = sessionState;
            }

            return View(sessionState.Model);
        }

        public ActionResult SetCount(int count)
        {
            var sessionState = Session[Setting.SESSION_PRODUCTS] as SessionState;
            if (sessionState == null || sessionState.SelectedViewModel == null) return RedirectToAction("Index");

            sessionState.SelectedViewModel.Count = count;
            Session[Setting.SESSION_PRODUCTS] = sessionState;

            return View("Index", sessionState.Model);
        }

        public ActionResult SelectProductViewModel(string selectedProduct)
        {
            try
            {
                SelectProduct(selectedProduct);
                return View("Index", (Session[Setting.SESSION_PRODUCTS] as SessionState)?.Model);
            }
            catch(InvalidOperationException)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult SelectProductViewModelRedemtion(string selectedProduct)
        {
            if (string.IsNullOrEmpty(selectedProduct))
                throw new ArgumentNullException(nameof(selectedProduct));

            try
            {
                SelectProduct(selectedProduct);
                return RedirectToAction("RedeemStampCard");
            }
            catch (InvalidOperationException)
            {
                return RedirectToAction("Index");
            }
        }

        private void SelectProduct(string selectedProduct)
        {
            if (string.IsNullOrEmpty(selectedProduct))
                throw new ArgumentNullException(nameof(selectedProduct));

            var sessionState = Session[Setting.SESSION_PRODUCTS] as SessionState;
            if (sessionState == null || sessionState.Model == null)
                throw new InvalidOperationException("The sessionstate does not contain a model and can theirfore not select any product");

            if (sessionState.SelectedViewModel != null)
                sessionState.SelectedViewModel.IsSelected = false;
            sessionState.SelectedViewModel = sessionState.Model.Where(vm => vm?.Product?.Productname == selectedProduct).FirstOrDefault();
            sessionState.SelectedViewModel.IsSelected = true;
            Session[Setting.SESSION_PRODUCTS] = sessionState;
        }

        public async Task<ActionResult> ShowStampGenerationQrCode()
        {
            var sessionState = Session[Setting.SESSION_PRODUCTS] as SessionState;
            if (sessionState == null || sessionState.Model == null) return RedirectToAction("Index");
            
            var stampcode = StampCodeProvider.GenerateStampCode((Dictionary<Product,int>)sessionState);
            var img = await ImageUtil.GetImageFromUrl(QrCodeGenerator.GetQrCodeUrl(stampcode));
            this.StampCodeService.AddStampcode(stampcode, (Dictionary<Product, int>)sessionState);

            return View(new ScanViewModel
            {
                Base64Img = Convert.ToBase64String(img),
                Stampcode = stampcode
            });
        }

        public async Task<ActionResult> RedeemStampCard()
        {
            var sessionState = Session[Setting.SESSION_PRODUCTS] as SessionState;
            if (sessionState == null || sessionState.Model == null) return RedirectToAction("Index");

            var stampcode = StampCodeProvider.GenerateRedeemCode(sessionState.SelectedViewModel.Product);
            var img = await ImageUtil.GetImageFromUrl(QrCodeGenerator.GetQrCodeUrl(stampcode));
            var products = sessionState.Model;
            this.StampCodeService.AddReedemtionStampcode(stampcode, sessionState.SelectedViewModel.Product);

            return View(new ScanViewModel
            {
                Base64Img = Convert.ToBase64String(img),
                Stampcode = stampcode,
                Products = products
            });
        }

        public ActionResult Clear()
        {
            Session[Setting.SESSION_PRODUCTS] = null;
            return RedirectToAction("Index");
        }
    }

    public class SessionState
    {
        public IList<ProductViewModel> Model { get; set; }
        public ProductViewModel SelectedViewModel { get; set; }

        public static explicit operator Dictionary<Product,int>(SessionState session)
        {
            if (session == null) throw new ArgumentNullException(nameof(session));
            return session.Model?.ToDictionary(vm => vm.Product, vm => vm.Count);
        }
    }
}

Stampit/Stampit.Webapp/Views/KioskMode/Index.cshtml
@using Stampit.Webapp.Models;
@using Stampit.CommonType;
@model IEnumerable<ProductViewModel>

@{
    ViewBag.Title = "Stampit Kiosk";
}
@if (string.IsNullOrEmpty(Session[Setting.SESSION_COMPANY]?.ToString()))
{
	<br />
	<h1>No Company selected</h1>
}
else
{
	<div class="jumbotron row">
		<h1 class="col-xs-6">STAMPIT KIOSK</h1>
		<div class="col-xs-6">
			<button type="button" class="btn btn-lg btn-primary btn-default btn-use-stamp" onclick="location.href='@Url.Action("RedeemStampCard", "KioskMode")'">Stempelkarte einlösen</button>
		</div>
	</div>

	<div class="flexcontainer">
		<div class="flexcol">
			<div class="products">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h3 class="panel-title">Produkte</h3>
					</div>
					<div class="panel-body">
						@if (Model != null)
						{
							foreach (var productEntry in Model)
							{
								<div class="row">
									<button type="button" class="btn btn-lg btn-primary @GetProductButtonClass(productEntry) btn-product" onclick="location.href='@Url.Action("SelectProductViewModel", "KioskMode", new { selectedProduct = productEntry.Product.Productname })'">
										<div class="row product-detail-container">
											<span class="text-left col-xs-9 product-detail-name">@productEntry.Product.Productname</span>
											@if (productEntry.Count != 0)
											{
												<span class="text-right col-xs-2 bubble">@productEntry.Count</span>
	                                        }
										</div>
									</button>
								</div>
							}
						}
						else
						{
							<div class="row" />
						}
					</div>
				</div>
			</div>
		</div>
		<div class="flexcol">
			<div class="flexcontainer">
				<div class="row">
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 1 })'">1</button>
					</div>
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 4 })'">4</button>
					</div>
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 7 })'">7</button>
					</div>
				</div>
				<div class="row">
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 2 })'">2</button>
					</div>
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 5 })'">5</button>
					</div>
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 8 })'">8</button>
					</div>
				</div>
				<div class="row">
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 3 })'">3</button>
					</div>
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-success" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 6 })'">6</button>
					</div>
					<div class="calcbtn">
						<button type="button" class="btn btn-xlg btn-primary btn-cancel" onclick="location.href='@Url.Action("SetCount", "KioskMode", new { count = 0 })'">C</button>
					</div>
				</div>
			</div>
		</div>
		<div class="flexcol"><button type="button" class="btn btn-lg btn-primary btn-default btn-cash-stamp" onclick="location.href='@Url.Action("ShowStampGenerationQrCode", "KioskMode")'">Stempel erzeugen</button></div>
	</div>

	@functions {

		string GetProductButtonClass(ProductViewModel productEntry)
		{
			return (productEntry?.IsSelected ?? false) ? "btn-selected" : "btn-danger";
		}
	}
}

Stampit/Stampit.Webapp/Views/KioskMode/RedeemStampCard.cshtml
@using Stampit.Webapp.Models
@model ScanViewModel

@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script type="text/javascript">
        var isLastValid = true;

        $(function () {
            var con = $.hubConnection();
            var hub = con.createHubProxy('scan');
            hub.on('onScan', function (code,valid) {
                isLastValid = valid;
                var thisPageCode = "@Model.Stampcode";
                if(code == thisPageCode)
                {
                    if(valid)
                    {
                        $('#code').text('Code wurde gescannt!');
                        $('#successModel').modal('show');
                    }
                    else
                    {
                        $('#failedModel').modal('show');
                    }
                }
            });
            con.start(function () {

            });
        });
    </script>
}

<div class="flexcontainer">
    <div class="col-md-3">
        <div class="products">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Produkte</h3>
                </div>
                <div class="panel-body">
                    @if (Model != null && Model.Products != null)
                    {
                        foreach (var productEntry in Model.Products)
                        {
                            <div class="row">
                                <button type="button" class="btn btn-lg btn-primary @GetProductButtonClass(productEntry) btn-product" onclick="location.href='@Url.Action("SelectProductViewModelRedemtion", "KioskMode", new { selectedProduct = productEntry.Product.Productname })'">
                                    <div class="row product-detail-container">
                                        <span class="text-left col-xs-9 product-detail-name">@productEntry.Product.Productname</span>
                                    </div>
                                </button>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="row" />
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-9 text-center">
        <h2>Bitte scannen Sie den QRCode mit der Stampit App um die Stempelkarte einzulösen</h2>
        <h3 id="code">Der Code (@Model.Stampcode) gilt für das Produkt <b>@Model.Products.Where(p => p.IsSelected).FirstOrDefault().Product.Productname</b></h3>
        <br />
        <img src="@($"data:image/png;base64,{Model.Base64Img}")" />
        <br /><br />
        <button type="button" class="btn btn-lg btn-primary btn-default btn-cash-stamp" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'">Zurück</button>
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="successModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Scan war erfolgreich</h4>
            </div>
            <div class="modal-body text-center">
                <img src="http://vignette1.wikia.nocookie.net/whentheycry/images/2/2a/Check.png/revision/latest?cb=20120629163937" width="200" height="200" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-lg" data-dismiss="modal" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'">Zurück</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" role="dialog" id="failedModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Sie haben leider nicht genügend Stempel für dieses Produkt</h4>
            </div>
            <div class="modal-body text-center">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Dialog-error-round.svg/2000px-Dialog-error-round.svg.png" width="200" height="200" />
            </div>
            <div class="modal-footer row">
                <div class="col-md-6 text-center">
                    <button type="button" class="btn btn-default btn-lg" data-dismiss="modal" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'">Zurück</button>
                </div>
                <div class="col-md-6 text-center">
                    <button type="button" class="btn btn-default btn-lg" data-dismiss="modal" onclick="location.href='@Url.Action("RedeemStampCard", "KioskMode", new { })'">Erneut versuchen</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@functions {

    string GetProductButtonClass(ProductViewModel productEntry)
    {
        return (productEntry?.IsSelected ?? false) ? "btn-selected" : "btn-danger";
    }
}

Stampit/Stampit.Webapp/Views/KioskMode/ShowStampGenerationQrCode.cshtml
@using Stampit.Webapp.Models
@model ScanViewModel

@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script type="text/javascript">
        var isLastValid = true;

        $(function () {
            var con = $.hubConnection();
            var hub = con.createHubProxy('scan');
            hub.on('onScan', function (code,valid) {
                isLastValid = valid;
                var thisPageCode = "@Model.Stampcode";
                //if(code == thisPageCode)
                {
                    if(valid)
                    {
                        $('#code').text('Code wurde gescannt!');
                        $('#successModel').modal('show');
                    }
                    else
                    {
                        $('#failedModel').modal('show');
                    }
                }
            });
            con.start(function () {

            });
        });
    </script>
}

<div class="modal fade" tabindex="-1" role="dialog" id="successModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Scan war erfolgreich</h4>
            </div>
            <div class="modal-body text-center">
                <img src="http://vignette1.wikia.nocookie.net/whentheycry/images/2/2a/Check.png/revision/latest?cb=20120629163937" width="250" height="250" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-lg" data-dismiss="modal" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'">Zurück</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" tabindex="-1" role="dialog" id="failedModel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Scan war nicht erfolgreich</h4>
            </div>
            <div class="modal-body text-center">
                <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Dialog-error-round.svg/2000px-Dialog-error-round.svg.png" width="200" height="200" />
            </div>
            <div class="modal-footer row">
                <div class="col-md-6">
                    <button type="button" class="btn btn-default btn-lg" data-dismiss="modal" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'">Zurück</button>
                </div>
                <div class="col-md-6">
                    <button type="button" class="btn btn-default btn-lg" data-dismiss="modal" onclick="location.href='@Url.Action("RedeemStampCard", "KioskMode", new { })'">Erneut versuchen</button>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="text-center col-md-12">
    <h2>Bitte scannen Sie den QRCode mit der Stampit App um den Stempel zu erhalten</h2>
    <h2 id="code">Code: @Model.Stampcode</h2>
    <br />
    <img src="@($"data:image/png;base64,{Model.Base64Img}")" />
    <br /><br />
    <button type="button" class="btn btn-lg btn-primary btn-default btn-cash-stamp" onclick="location.href='@Url.Action("Clear", "KioskMode", new { })'">Zurück</button>
</div>