Stampit/Stampit.Webapp/Models/UsersViewModel.cs
using Stampit.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Models
{
    public class UsersViewModel
    {
        public Businessuser User{ get; set; }
        public IEnumerable<SelectListItem> Roles = new List<SelectListItem>();
    }
}

Stampit/Stampit.Webapp/Controllers/CompanyDataController.cs
using Stampit.Entity;
using Stampit.Logic.Interface;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Stampit.CommonType;
using Stampit.Webapp.Models;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "Manager")]
    public class CompanyDataController : Controller
    {
        private ICompanyRepository CompanyRepository { get; }

        public CompanyDataController(ICompanyRepository companyRepository)
        {
            this.CompanyRepository = companyRepository;
        }

        // GET: CompanyData
        public PartialViewResult Index()
        {
            var session = Session[Setting.SESSION_COMPANY].ToString();
            var company = CompanyRepository.FindByIdAsync(session).Result;
            return PartialView(company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveData(Company company)
        {
            if (company == null) return RedirectToAction("Index", "Profile");

            try
            {
                //persist data 
                Company com = await CompanyRepository.FindByIdAsync(company.Id);
                com.CompanyName = company.CompanyName;
                com.ContactAddress = company.ContactAddress;
                com.ContactName = company.ContactName;
                com.Description = company.Description;

                await CompanyRepository.CreateOrUpdateAsync(com);
                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return RedirectToAction("Index", "Profile");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveImage(HttpPostedFileBase file)
        {
            try
            {
                Company com = await CompanyRepository.FindByIdAsync(Session[Setting.SESSION_COMPANY].ToString());
                
                // Verify that the user selected a file
                if (file != null && file.ContentLength > 0)
                {
                    com.Blob = new Blob
                    {
                        Id = Guid.NewGuid().ToString().Replace("-", ""),
                        CreatedAt = DateTime.Now,
                        Filename = file.FileName,
                        ContentType = file.ContentType,
                        Content = await CommonType.ImageUtil.GetImageFromStream(file.InputStream)
                    };

                    await CompanyRepository.CreateOrUpdateAsync(com);
                }
            }
            catch
            {
                return RedirectToAction("Index", "Profile");
            }

            return RedirectToAction("Index", "Profile");
        }
    }
}

Stampit/Stampit.Webapp/Controllers/StoresController.cs
using Stampit.CommonType;
using Stampit.Entity;
using Stampit.Logic.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "Manager")]
    public class StoresController : Controller
    {
        private IStoreRepository StoreRepository { get; }
        private ICompanyRepository CompanyRepository { get; }

        public StoresController(IStoreRepository storeRepository, ICompanyRepository companyRepository)
        {
            this.StoreRepository = storeRepository;
            this.CompanyRepository = companyRepository;
        }

        // GET: Stores
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult StoresMap()
        {
            string companyID = Session[Setting.SESSION_COMPANY].ToString();
            var storelist = StoreRepository.GetAllAsync(0).Result;
            return PartialView(storelist.Where(com => com.CompanyId == companyID));
        }

        public PartialViewResult StoresList()
        {
            string companyID = Session[Setting.SESSION_COMPANY].ToString();
            var storelist = StoreRepository.GetAllAsync(0).Result;
            return PartialView(storelist.Where(com => com.CompanyId == companyID));
        }
        
        // GET: Stores/Create
        public ActionResult Create(double? lat=null, double? lng=null)
        {
            if(lat==null||lng==null) return RedirectToAction("Index", "Profile");

            Store s = new Store();
            s.Latitude = lat.Value;
            s.Longitude = lng.Value;

            return View(s);
        }

        // POST: Stores/Create
        [HttpPost]
        public async Task<ActionResult> Create(Store store)
        {
            if (store == null) return View();

            try
            {
                string companyID = Session[Setting.SESSION_COMPANY].ToString();
                var company = await CompanyRepository.FindByIdAsync(companyID);

                store.CompanyId = companyID;
                await StoreRepository.CreateOrUpdateAsync(store);

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        // GET: Stores/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var store = await StoreRepository.FindByIdAsync(id);
            return View(store);
        }

        // POST: Stores/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(Store item)
        {
            if (item == null) return View();
            var store = await StoreRepository.FindByIdAsync(item.Id);

            try
            {
                store.Address = item.Address;
                store.Description = item.Description;
                store.Latitude = item.Latitude;
                store.Longitude = item.Longitude;
                store.StoreName = item.StoreName;

                await StoreRepository.CreateOrUpdateAsync(store);
                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        // GET: Stores/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var store = await StoreRepository.FindByIdAsync(id);
            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Store store)
        {
            try
            {
                await StoreRepository.Delete(store);
                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Stampit/Stampit.Webapp/Controllers/UsersController.cs
using Stampit.CommonType;
using Stampit.Entity;
using Stampit.Logic.Interface;
using Stampit.Webapp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "Manager")]
    public class UsersController : Controller
    {
        private IBusinessuserRepository BusinessuserRepository { get; }
        private IRoleRepository RoleRepository { get; }
        private ICompanyRepository CompanyRepository { get; }

        private static IEnumerable<Role> Roles { get; set; }

        public UsersController(IBusinessuserRepository businessuserRepository, IRoleRepository roleRepository, ICompanyRepository companyRepository)
        {
            this.BusinessuserRepository = businessuserRepository;
            this.RoleRepository = roleRepository;
            this.CompanyRepository = companyRepository;
        }

        // GET: Users
        public PartialViewResult Index()
        {
            string companyID = Session[Setting.SESSION_COMPANY].ToString();
            var userlist = BusinessuserRepository.GetAllAsync(0).Result;
            return PartialView(userlist.Where(user => user.CompanyId == companyID));
        }

        // GET: Products/Create
        public async Task<ActionResult> Create()
        {
            var user = await GetUsersViewModel("");
            return View(user);
        }

        // POST: Products/Create
        [HttpPost]
        public async Task<ActionResult> Create(UsersViewModel item)
        {
            if (item == null) return View();

            try
            {
                string companyID = Session[Setting.SESSION_COMPANY].ToString();
                item.User.CompanyId = companyID;

                await BusinessuserRepository.CreateOrUpdateAsync(item.User);

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var user = await GetUsersViewModel(id);
            return View(user);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UsersViewModel item)
        {
            if (item == null) return View();

            //TODO: update attributes

            try
            {
                var user = await BusinessuserRepository.FindByIdAsync(item.User.Id);
                user.Id = item.User.Id;
                user.RoleId = item.User.RoleId;
                user.FirstName = item.User.FirstName;
                user.LastName = item.User.LastName;
                user.MailAddress = item.User.MailAddress;

                await BusinessuserRepository.CreateOrUpdateAsync(user);

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }
        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var user = await BusinessuserRepository.FindByIdAsync(id);
            return View(user);
        }

        // POST: Products/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Businessuser user)
        {
            try
            {
                await BusinessuserRepository.Delete(user);
                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        private async Task<UsersViewModel> GetUsersViewModel(string id)
        {
            UsersViewModel viewModel = new UsersViewModel();

            if (Roles == null) {
                Roles = await RoleRepository.GetAllAsync(0);
                Roles = Roles.Where(role => !role.RoleName.Equals("Admin"));
            }

            if(id!=null && !id.Equals("")) {
                var user = await BusinessuserRepository.FindByIdAsync(id);
                viewModel.User = user;
            }

            viewModel.Roles = Roles.Select(r => new SelectListItem
            {
                Text = r.RoleName,
                Value = r.Id
            });

            return viewModel;
        }
    }
}

Stampit/Stampit.Webapp/Views/CompanyData/Delete.cshtml
@model Stampit.Entity.Product

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Productname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Productname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequiredStampCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequiredStampCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BonusDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BonusDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxDuration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxDuration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CompanyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CompanyId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Stampit/Stampit.Webapp/Views/CompanyData/Edit.cshtml
@model Stampit.Entity.Product

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Productname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Productname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Productname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequiredStampCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequiredStampCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequiredStampCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BonusDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BonusDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BonusDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxDuration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxDuration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxDuration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück", "Index", "CompanyData", null, null, "Produkte", null, null)
</div>

Stampit/Stampit.Webapp/Views/CompanyData/Index.cshtml
@using Stampit.CommonType;
@model Stampit.Entity.Company
<div class="container">
	<div class="row">
		<div class="col-md-6">
			@using (Html.BeginForm("SaveData", "CompanyData", FormMethod.Post))
			{
				@Html.AntiForgeryToken()

				<div class="form-horizontal">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@Html.HiddenFor(model => model.Id)

					<div class="form-group">
						@Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.ContactAddress, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.ContactAddress, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.ContactAddress, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
							@Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
						<div class="col-md-10">
							@Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
							@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
						</div>
					</div>

					<div class="form-group">
						<div class="col-md-offset-2 col-md-10">
							<input type="submit" value="Save" class="btn btn-default">
						</div>
					</div>
				</div>
			}
		</div>
		<div class="col-md-6">
			@using (Html.BeginForm("SaveImage", "CompanyData", FormMethod.Post, new { enctype = "multipart/form-data" }))
			{
				@Html.AntiForgeryToken()

				<div class="form-horizontal">
					@Html.ValidationSummary(true, "", new { @class = "text-danger" })
					@Html.HiddenFor(model => model.Id)
					<div class="form-group">
						<div class="col-md-12">
							@if (Model.Blob == null)
							{
								<img src="~/Content/Images/Unknown.png" width="200" height="200" />
							}
							else
							{
								<img src="@($"data:image/png;base64,{Model.Blob.Content.ToBase64()}")" width="200" height="200" />
							}
						</div>
					</div>
					<div class="form-group">
						<input id="file" type="file" name="file" class="btn btn-default">
						<br />
						<input type="submit" value="Save" class="btn btn-default">
					</div>
				</div>
			}
		</div>
	</div>
</div>

Stampit/Stampit.Webapp/Views/CompanyData/Stores.cshtml
@using Newtonsoft.Json;
@using Stampit.Entity;
@model IEnumerable<Store>
<script src="http://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>

<!-- This css is to ensure that the google map contols (zoom bar etc) show and size correctly. -->
<style>
	#map_canvas img {
		max-width: none;
	}
</style>

<!-- This css is to give a nice big popup "info window" when a marker is clicked on the map -->
<style>
	.infoDiv {
		height: 100px;
		width: 200px;
		-webkit-user-select: none;
		background-color: white;
	}
</style>
<!-- This is the div that will contain the Google Map -->
<div id="map_canvas" style="height: 600px;"></div>

<!-- Enclose the Javascript in a "section" so that it is rendered in the correct order after scripts have been loaded etc -->
		<script type="text/javascript">

			$(document).ready(function () {
				Initialize();
			});

			// Where all the fun happens
			function Initialize() {

				// Google has tweaked their interface somewhat - this tells the api to use that new UI
				google.maps.visualRefresh = true;

				var modeldata = @Html.Raw(JsonConvert.SerializeObject(Model));
				
				var Linz = new google.maps.LatLng(48.303487, 14.288781);

				// These are options that set initial zoom level, where the map is centered globally to start, and the type of map to show
				var mapOptions = {
					zoom: 14,
					center: Linz,
					mapTypeId: google.maps.MapTypeId.ROADMAP
					
				};

				// This makes the div with id "map_canvas" a google map
				var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

				// Using the JQuery "each" selector to iterate through the JSON list and drop marker pins
	
				$.each(modeldata, function (i, item) {
				
					var marker = new google.maps.Marker({
						'position': new google.maps.LatLng(item.Latitude.toString(),item.Longitude.toString()),
						'map': map,
						'title': item.Address
					});

					// Make the marker-pin blue!
					marker.setIcon('http://maps.google.com/mapfiles/ms/icons/red-dot.png')

					contentString = "<div class='infoDiv'><h2>" + item.Company.CompanyName + "</h2>" + "<div><a href='#' id='address' data-type='text' data-placement='right' data-title='Enter address'>"+item.Address+"</a>"
					content = "<div class='info'><iframe src='CompanyData/MapsEdit'></iframe></div>"
					// put in some information about each json object - in this case, the opening hours.
					var infowindow = new google.maps.InfoWindow();
					infowindow.setContent(content);
	
					// finally hook up an "OnClick" listener to the map so it pops up out info-window when the marker-pin is clicked!
					google.maps.event.addListener(marker, 'click', function () {
						infowindow.open(map, marker);
					});

				})

				// This event listener will call addMarker() when the map is clicked.
				map.addListener('click', function(event) {
					var marker = new google.maps.Marker({
						'position': event.latLng,
						'map': map,
						'title': "Address"
					});

					// put in some information about each json object - in this case, the opening hours.
					var infowindow = new google.maps.InfoWindow({
						content: "<div class='infoDiv'><h2>" + "CompanyName" + "</h2>" + "<div><h4>" +"Address" + "</h4></div>" + "<div><h5>"+ "Description"+ "</h5></div></div>"
					});

					google.maps.event.addListener(marker, 'click', function () {
						infowindow.open(map, marker);
					});

				});

			}
		</script>

Stampit/Stampit.Webapp/Views/CompanyData/Users.cshtml
@model IEnumerable<Stampit.Entity.Businessuser>
@{
	Layout = "~/Views/Shared/_LayoutPartial.cshtml";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RoleId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RoleId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<p>
	<input type="submit" value="Create new" class="btn btn-default" />
</p>