Stampit/Stampit.Webapp/Models/UsersViewModel.cs
using Stampit.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Models
{
    public class UsersViewModel
    {
        public Businessuser User{ get; set; }
        public IEnumerable<SelectListItem> Roles = new List<SelectListItem>();
    }
}

Stampit/Stampit.Webapp/Controllers/ProductsController.cs
using Stampit.CommonType;
using Stampit.Entity;
using Stampit.Logic.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "Manager")]
    public class ProductsController : Controller
    {
        private IProductRepository ProductRepository { get; }
        private ICompanyRepository CompanyRepository { get; }

        public ProductsController(IProductRepository productRepository, ICompanyRepository companyRepository)
        {
            this.ProductRepository = productRepository;
            this.CompanyRepository = companyRepository;
        }
        // GET: Products
        public PartialViewResult Index()
        {
            string companyID = Session[Setting.SESSION_COMPANY].ToString();
            var productlist = ProductRepository.GetAllAsync(0).Result;
            return PartialView(productlist.Where(prod => prod.CompanyId == companyID));
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Product product)
        {
            if (product == null) return View();

            try
            {
                string companyID = Session[Setting.SESSION_COMPANY].ToString();

                product.CompanyId = companyID;
                await ProductRepository.CreateOrUpdateAsync(product);

                Session[Setting.SESSION_PRODUCTS] = null;

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(id)) return View();

            var product = await ProductRepository.FindByIdAsync(id);
            return View(product);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Product product)
        {
            if (product == null) return View();
            var prod = await ProductRepository.FindByIdAsync(product.Id);

            try
            {
                prod.Active = product.Active;
                prod.BonusDescription = product.BonusDescription;
                prod.MaxDuration = product.MaxDuration;
                prod.Price = product.Price;
                prod.Productname = product.Productname;
                prod.RequiredStampCount = product.RequiredStampCount;

                await ProductRepository.CreateOrUpdateAsync(prod);

                Session[Setting.SESSION_PRODUCTS] = null;

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(string productid)
        {
            var product = await ProductRepository.FindByIdAsync(productid);
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Product product)
        {
            try
            {
                await ProductRepository.Delete(product);
                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }
    }
}

Stampit/Stampit.Webapp/Controllers/UsersController.cs
using Stampit.CommonType;
using Stampit.Entity;
using Stampit.Logic.Interface;
using Stampit.Webapp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Stampit.Webapp.Controllers
{
    [StampitAuthorize(Roles = "Manager")]
    public class UsersController : Controller
    {
        private IBusinessuserRepository BusinessuserRepository { get; }
        private IRoleRepository RoleRepository { get; }
        private ICompanyRepository CompanyRepository { get; }

        private static IEnumerable<Role> Roles { get; set; }

        public UsersController(IBusinessuserRepository businessuserRepository, IRoleRepository roleRepository, ICompanyRepository companyRepository)
        {
            this.BusinessuserRepository = businessuserRepository;
            this.RoleRepository = roleRepository;
            this.CompanyRepository = companyRepository;
        }

        // GET: Users
        public PartialViewResult Index()
        {
            string companyID = Session[Setting.SESSION_COMPANY].ToString();
            var userlist = BusinessuserRepository.GetAllAsync(0).Result;
            return PartialView(userlist.Where(user => user.CompanyId == companyID));
        }

        // GET: Products/Create
        public async Task<ActionResult> Create()
        {
            var user = await GetUsersViewModel("");
            return View(user);
        }

        // POST: Products/Create
        [HttpPost]
        public async Task<ActionResult> Create(UsersViewModel item)
        {
            if (item == null) return View();

            try
            {
                string companyID = Session[Setting.SESSION_COMPANY].ToString();
                item.User.CompanyId = companyID;

                await BusinessuserRepository.CreateOrUpdateAsync(item.User);

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        // GET: Products/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var user = await GetUsersViewModel(id);
            return View(user);
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UsersViewModel item)
        {
            if (item == null) return View();

            //TODO: update attributes

            try
            {
                var user = await BusinessuserRepository.FindByIdAsync(item.User.Id);
                user.Id = item.User.Id;
                user.RoleId = item.User.RoleId;
                user.FirstName = item.User.FirstName;
                user.LastName = item.User.LastName;
                user.MailAddress = item.User.MailAddress;

                await BusinessuserRepository.CreateOrUpdateAsync(user);

                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }
        // GET: Products/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var user = await BusinessuserRepository.FindByIdAsync(id);
            return View(user);
        }

        // POST: Products/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Businessuser user)
        {
            try
            {
                await BusinessuserRepository.Delete(user);
                return RedirectToAction("Index", "Profile");
            }
            catch
            {
                return View();
            }
        }

        private async Task<UsersViewModel> GetUsersViewModel(string id)
        {
            UsersViewModel viewModel = new UsersViewModel();

            if (Roles == null) {
                Roles = await RoleRepository.GetAllAsync(0);
                Roles = Roles.Where(role => !role.RoleName.Equals("Admin"));
            }

            if(id!=null && !id.Equals("")) {
                var user = await BusinessuserRepository.FindByIdAsync(id);
                viewModel.User = user;
            }

            viewModel.Roles = Roles.Select(r => new SelectListItem
            {
                Text = r.RoleName,
                Value = r.Id
            });

            return viewModel;
        }
    }
}

Stampit/Stampit.Webapp/Views/Users/Create.cshtml
@model Stampit.Webapp.Models.UsersViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.User.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.User.MailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.MailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.MailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

		<div class="form-group">
			@Html.LabelFor(model => model.User.Role.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownListFor(model => model.User.RoleId, Model.Roles, "-- Select Role --", new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.User.RoleId, "", new { @class = "text-danger" })
			</div>
		</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to the list", "Index", "Profile", null, null, "Users", null, null)
</div>

Stampit/Stampit.Webapp/Views/Users/Delete.cshtml
@model Stampit.Entity.Businessuser

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role.RoleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role.RoleName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to the list", "Index", "Profile", null, null, "Products", null, null)
        </div>
    }
</div>

Stampit/Stampit.Webapp/Views/Users/Edit.cshtml
@model Stampit.Webapp.Models.UsersViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()  
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.User.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.User.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.User.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.User.MailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User.MailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.MailAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.User.Role.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(model => model.User.RoleId, Model.Roles, "-- Select Role --", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
	@Html.ActionLink("Back to the list", "Index", "Profile", null, null, "Users", null, null)
</div>

Stampit/Stampit.Webapp/Views/Users/Index.cshtml
@model IEnumerable<Stampit.Entity.Businessuser>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role.RoleName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role.RoleName)
        </td>
        <td>
			@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>
<p>
	@Html.ActionLink("Create new", "Create", null, new { @class = "btn btn-default" })
</p>